pipeline {
    environment {
        dockerrepo = "jegandocker/demonginx"
        dockerHubCredentials = 'dockerlogin'
    }
 
    agent any
 
    stages {
        stage('Cloning Git') {
            steps {
                git([url: 'https://github.com/jeganarepo/coderepo', branch: 'main'])
            }
        }
    } 

    post {
        always {
            cleanWs()
        }
    }
}