pipeline {
    environment {
        dockerrepo           = "jegandocker/demonginx"
        dockerHubCredentialsId = 'dockerlogin'
    }
 
    agent any
 
    stages {
        stage('Cloning Git') {
            steps {
                git([url: 'https://github.com/jeganarepo/coderepo', branch: 'main'])
            }
        }
        stage('Docker Build') {
            steps {
                sh 'cd docker-image; pwd; ls -l'
                sh 'docker build -t ${dockerrepo}:v1 .'
            }
        }
        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.dockerHubCredentialsId, passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                sh 'docker push shanem/spring-petclinic:latest'
                }
            }
        }
    } 

    post {
        always {
            cleanWs()
        }
    }
}