name: Check out code

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: List the git workspace
        run: ls -la "${{github.workspace}}"
      - name: List the repo content 
        uses: actions/checkout@v4
      - name: List the git workspace after checkout
        run: ls -la "${{github.workspace}}"
        
  another_job:
    runs-on: ubuntu-latest
    steps:
      - name: List the git workspace
        run: ls -la "${{github.workspace}}"
