name: Docker github action

on:
  workflow_dispatch:  # This event triggers the workflow manually
env:
  DOCKER_HUB_USERNAME: jegandocker
  IMAGE_NAME: nginx-demo
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cpde
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
          
      - name: Build and push image to docker hub
        uses: docker/build-push-action@v6
        with:
          context: docker-image
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          label: latest
          
  another_job:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: List the git workspace
        run: ls -la "${{github.workspace}}"
