name: Docker github action

on:
  workflow_dispatch:  # This event triggers the workflow manually
env:
  DOCKER_HUB_USERNAME: jegandocker
  IMAGE_NAME: nginx-demo
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: json
          output-file: ${{github.workspace}}/hadolint.json
          
      - name: List repo  
        run: cat ${{github.workspace}}/hadolint.json
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: hadolint
          path: ${{ github.workspace }}/hadolint.json       

        
      
